### ISSUE TITLE
plugin does not load

### ISSUE THREAD

**Issue by titustitus98** [Efnilite/Skematic#6]
Hi I have installed skematic on my server but it shows in red in /pl how do I fix that?

**Comment by Efnilite** [comment]
Are there any errors on startup?

**Comment by JeroenoBoy** [comment]
Titustitus98 Maybe you dont have FAWE, without it mine didnt work either

**Comment by Efnilite** [comment]
Closing this for now, since @titustitus98 isn't really giving me much info to work with. 🤔
