### ISSUE TITLE
Paste doesnt work

### ISSUE THREAD

**Issue by JeroenoBoy** [Efnilite/Skematic#8]
paste doesnt work for me, Server version: 1.12.2. code: paste skematic "plugins/WorldEdit/schematics/41043b4c-37f7-483e-b8e5-8131655289ca/Town_Hall_1.schematic" at player
https://gyazo.com/d7ed4d311c8b61d3f26c0916bbf67706

**Comment by Efnilite** [comment]
What's your Skematic version? 2.1 doesn't work on 1.12, but I'll try to add 1.12 support to 2.2 asap

**Comment by JeroenoBoy** [comment]
2.1

**Comment by Efnilite** [comment]
`2.1 doesn't work on 1.12, but I'll try to add 1.12 support to 2.2 asap`
